### PR TITLE
Add stationary mode, xcontrol, dev mode, and the option to make stationary mode robot side or app side

### PR DESCRIPTION
**Pull request by SkyeOfBreeze**
Also able to select what commands will be blocked in stationary mode

### CODE REVIEW

**Comment by SkyeOfBreeze** [comment]
fixes https://github.com/remotv/controller-for-android/issues/20 and also allows button commands to be parsed as commands as well, such as xcontrol, which uses `xcontrol ~ 60` for the user who pressed the button for 60 seconds

**Comment by SkyeOfBreeze** [comment]
Exclusive Control
- `/xcontrol user 60`: give user `user` control of robot for 60 seconds
- `/xcontrol ~ 60` (button): give user who pressed the button exclusive control for 60 seconds
- `/xcontrol user`: user `user` gets exclusive control indefinitely or until the robot reboots
- `/xcontrol off`: turn off exclusive control

Dev mode
- `/devmode on`: turn on devmode
- `/devmode off`: turn off devmode

Stationary mode:
The robot controls this, unless set in the app settings to be handled locally. The option exists for both since some hardware is not programmable, such as a sabertooth serial controller. In the case that the app controls it, the list of restricted controls are configurable as well
- `stationary on`: turn on stationary (table) mode
- `stationary off`: turn off stationary mode

**Comment by SkyeOfBreeze** [comment]
@bmorrison4 Is this how the python controller behaves?

**Comment by SkyeOfBreeze** [comment]
devmode is currently broken

**Comment by SkyeOfBreeze** [comment]
not really a good way to get user other than hard coding right now since I show up as just a global_moderator when hitting a button

**Comment by Nocturnal42** [comment]
Stationary can also be called as a chat command without argument to toggle it on / off in the python controller. It also duplicated as the ‘table’ chat command since that’s what it was called under the old controller and people aren’t great at change. 

Dev mode is trickier. Code wise at the base level it’s not really any different to exclusive control or whitelisting commands. Where it gets tricky is that it may be implemented server side as it was on LR.

**Comment by SkyeOfBreeze** [comment]
I will be adding the `/table on` as well, and will probably keep using that since it is quicker to type

**Pull request merged**
